name: Docker_Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
         az acr build -r jobot1 --image bot-test:latest .


      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resourceGroupName: 'devia_25'
          containerGroupName: 'mycontainer'
          image: 'jobot1.azurecr.io/bot-test:latest'
          registryLoginServer: 'jobot1.azurecr.io'
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
